### ISSUE TITLE
crashes on Poco F1

### ISSUE THREAD

**Issue by gargamel17** [kl3jvi/sysinfo_app#3]
When launcging app on Poco with LOS 18, it immediately crashes

Log :

FATAL EXCEPTION: main
Process: com.kl3jvi.sysinfo, PID: 31337
java.lang.SecurityException: getDataNetworkTypeForSubscriber
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8768)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3031)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2995)
	at h1.e.C(:40)
	at androidx.fragment.app.Fragment.M(Unknown Source:15)
	at androidx.fragment.app.e.e0(:29)
	at androidx.fragment.app.e.c0(Unknown Source:49)
	at androidx.fragment.app.e.d0(Unknown Source:42)
	at androidx.fragment.app.a.h(:6)
	at androidx.fragment.app.e.R(:7)
	at androidx.fragment.app.e.j0(Unknown Source:88)
	at l0.j.b(:3)
	at androidx.viewpager.widget.ViewPager.q(:8)
	at androidx.viewpager.widget.ViewPager.onMeasure(:1)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.s(Unknown Source:0)
	at f2.d.i(:6)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(:19)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(:8)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3402)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2246)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2504)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by kl3jvi** [comment]
I have an Idea why that happens, its an issue with android 11 accessing data that is not allowed in this version, I will fix it, thanks!!
